# Generated by Django 5.1.4 on 2025-07-21 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_item_brand_item_code_item_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='item',
            name='code',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image_url',
        ),
    ]
